[Settings]
ID = 'localhost-proxy'

[[redirects]]
from = "/:domain.localhost"
to = "http://:domain.localhost/"
status = 301

[[redirects]]
from = "/*"
to = "https://duckduckgo.com/:splat"
status = 301
